[project]
name = "job-recommend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apify-client",
    "gemini",
    "pymupdf",
    "python-dotenv",
    "streamlit",
]
